#pragma once
#include "py/runtime.h"
#include <stdlib.h>
#include "py/binary.h"
#include "py/obj.h"
#include "py/objarray.h"
#include "py/objstr.h"
#include "sasppu/sasppu.h"
#include "sasppu/help.h"
#include "display.h"

#include "sasppu_background.h"
#include "sasppu_cmath_state.h"
#include "sasppu_main_state.h"
#include "sasppu_sprite.h"

extern const mp_obj_fun_builtin_var_t sasppu_copy_sprite_obj;
extern const mp_obj_fun_builtin_var_t sasppu_copy_sprite_transparent_obj;
extern const mp_obj_fun_builtin_var_t sasppu_fill_sprite_obj;
extern const mp_obj_fun_builtin_var_t sasppu_blit_sprite_obj;
extern const mp_obj_fun_builtin_var_t sasppu_paletted_sprite_obj;
extern const mp_obj_fun_builtin_var_t sasppu_compressed_sprite_obj;
extern const mp_obj_fun_builtin_var_t sasppu_blit_sprite_transparent_obj;
extern const mp_obj_fun_builtin_var_t sasppu_paletted_sprite_transparent_obj;
extern const mp_obj_fun_builtin_var_t sasppu_compressed_sprite_transparent_obj;
extern const mp_obj_fun_builtin_var_t sasppu_draw_text_sprite_obj;
extern const mp_obj_fun_builtin_var_t sasppu_draw_text_next_sprite_obj;

extern const mp_obj_fun_builtin_var_t sasppu_copy_background_obj;
extern const mp_obj_fun_builtin_var_t sasppu_copy_background_transparent_obj;
extern const mp_obj_fun_builtin_var_t sasppu_fill_background_obj;
extern const mp_obj_fun_builtin_var_t sasppu_blit_background_obj;
extern const mp_obj_fun_builtin_var_t sasppu_paletted_background_obj;
extern const mp_obj_fun_builtin_var_t sasppu_compressed_background_obj;
extern const mp_obj_fun_builtin_var_t sasppu_blit_background_transparent_obj;
extern const mp_obj_fun_builtin_var_t sasppu_paletted_background_transparent_obj;
extern const mp_obj_fun_builtin_var_t sasppu_compressed_background_transparent_obj;
extern const mp_obj_fun_builtin_var_t sasppu_draw_text_background_obj;
extern const mp_obj_fun_builtin_var_t sasppu_draw_text_next_background_obj;

extern const mp_obj_fun_builtin_var_t sasppu_get_text_size_obj;

extern const mp_obj_fun_builtin_var_t sasppu_macro_mul_rgb555_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_cmath_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_rgb555_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_rgb555_cmath_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_rgb888_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_rgb888_cmath_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_grey555_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_grey555_cmath_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_mul_channel_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_r_channel_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_g_channel_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_b_channel_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_cmath_channel_obj;
extern const mp_obj_fun_builtin_fixed_t sasppu_macro_mul_col_obj;